### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by TheMolkaPL** [kukubaczek/MG_Core#1]
Źle używasz Mavena :P

Usuń folder `target` i plik `dependency-reduced-pom.xml` (ten ostatni to bug Mavena xd).
Stwórz plik w głównym folderze (tu gdzie masz `.git`) plik `.gitignore`; w środku wklej zawartość z tych plików:
- https://github.com/github/gitignore/blob/master/Java.gitignore (dla języka Java)
- https://github.com/github/gitignore/blob/master/Maven.gitignore (dla Mavena)

**Comment by kukubaczek** [comment]
Ja się wgl cieszę ze maven mi działa 😂

W dniu niedziela, 13 marca 2016 Molek notifications@github.com napisał(a):

**Comment by TheMolkaPL** [comment]
I kod źródłowy nie trzyma się w `src/main`, lecz w `src/main/java` :D Pliki resources są dobrze (`src/main/resources`).

**Comment by TheMolkaPL** [comment]
#2 to rozwiązuje, więc zamykam. ;)
